# Generated by Django 5.0.7 on 2024-07-30 14:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('svg_file', models.FileField(upload_to='uploads/icons/', verbose_name='fichier svg')),
            ],
            options={
                'verbose_name': 'Icône',
                'verbose_name_plural': 'Icônes',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('name_fr', models.CharField(max_length=50, verbose_name='nom fr')),
                ('description', models.CharField(max_length=500, verbose_name='description du projet')),
                ('description_fr', models.CharField(max_length=500, verbose_name='description du projet fr')),
                ('order', models.PositiveSmallIntegerField(verbose_name="ordre d'apparition")),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('name_fr', models.CharField(max_length=50, verbose_name='nom fr')),
            ],
            options={
                'verbose_name': 'Type de projet',
                'verbose_name_plural': 'Types de projets',
            },
        ),
        migrations.CreateModel(
            name='PortfolioLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('link', models.CharField(max_length=200, verbose_name='lien')),
                ('order', models.PositiveSmallIntegerField(verbose_name="ordre d'apparition")),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.icon', verbose_name='icône')),
            ],
            options={
                'verbose_name': 'Lien de portfolio',
                'verbose_name_plural': 'Liens de portfolio',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('image', models.ImageField(upload_to='uploads/images/', verbose_name='image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'Image de projet',
                'verbose_name_plural': 'Images de projet',
            },
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('url', models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='url')),
                ('order', models.PositiveSmallIntegerField(verbose_name="ordre d'apparition")),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.icon', verbose_name='icône')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'Lien de projet',
                'verbose_name_plural': 'Liens de projet',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.projecttype', verbose_name='type de projet'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('order', models.PositiveSmallIntegerField(verbose_name="ordre d'apparition")),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.icon', verbose_name='icône')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(to='portfolio.skill', verbose_name='compétences'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('name_fr', models.CharField(max_length=100, verbose_name='nom fr')),
                ('firstname', models.CharField(max_length=30, verbose_name='prénom')),
                ('lastname', models.CharField(max_length=30, verbose_name='nom')),
                ('job_title', models.CharField(max_length=50, verbose_name='titre de poste')),
                ('job_title_fr', models.CharField(max_length=50, verbose_name='titre de poste fr')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='email de contact')),
                ('about_description', models.CharField(max_length=500, verbose_name='description de la section à propos')),
                ('about_description_fr', models.CharField(max_length=500, verbose_name='description de la section à propos fr')),
                ('resume', models.FileField(upload_to='uploads/resume/', verbose_name='cv')),
                ('active', models.BooleanField(default=False, verbose_name='actif')),
                ('about_link', models.ManyToManyField(to='portfolio.portfoliolink', verbose_name='liens')),
                ('about_skill', models.ManyToManyField(to='portfolio.skill', verbose_name='compétences')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
    ]
