# Generated by Django 5.0.7 on 2024-07-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='avatar',
            field=models.ImageField(default='pop', upload_to='uploads/avatar', verbose_name='avatar'),
            preserve_default=False,
        ),
    ]
