# Generated by Django 5.0.7 on 2024-08-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_types',
            field=models.ManyToManyField(blank=True, to='portfolio.projecttype', verbose_name='types'),
        ),
    ]
