# Generated by Django 5.0.7 on 2024-08-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolio_project_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliolink',
            old_name='link',
            new_name='url',
        ),
    ]
